include: package:lints/recommended.yaml

linter:
  rules:
    sort_constructors_first: true
    prefer_single_quotes: true
    await_only_futures: true
    prefer_contains: true
    no_duplicate_case_values: true
    prefer_iterable_whereType: true
    unrelated_type_equality_checks: true
    valid_regexps: true
    file_names: true
    always_use_package_imports: true
    prefer_const_constructors: true
    flutter_style_todos: true
    depend_on_referenced_packages: false

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - " **/*.gr.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "**/*.pb.dart"
    - "**/*.pb.dart"
    - "**/*.pbenum.dart"
    - "**/*.pbjson.dart"
    - "**/*.pbserver.dart"
